version: '3'

services:
  notificationdb:
    image: postgres
    ports:
      - "5434:80"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    depends_on:
      - notificationdb