# Generated by Django 2.1 on 2018-09-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='body',
            new_name='message',
        ),
    ]
