# Generated by Django 2.1 on 2018-10-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20181014_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
