# Generated by Django 2.1 on 2018-10-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notificationsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
