# Generated by Django 2.1 on 2018-10-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20181015_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencynotifications',
            name='image',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
