# Generated by Django 2.1 on 2018-10-16 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notifications_image'),
        ('notifications', '0009_emergencynotifications_image'),
    ]

    operations = [
    ]
